name: rag-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pydantic>=2
  - uvicorn
  - pip:
      - fastapi
      - openai>=1.0.0
      - sentence-transformers
      - pdfminer.six
      - pymilvus>=2.4.0
      - FlagEmbedding>=1.2.10
      - faiss-cpu

